### ISSUE TITLE
The entire message bus structure needs to be refactored

### ISSUE THREAD

**Issue by TheWinrarz** [TheWinrarz/anders-game#8]
I tried to use a message bus architecture after reading about it in a blog.

I feel that my implementation of it is ugly and complicated, and needs to be refined

**Comment by DanielAustinLee** [comment]
Either I am implementing the message bus the wrong way or it is entirely unnecessary. 

Supposedly it keeps coupling of systems low by having them communicate via a bus. However it seems like a lot of messages is clogging up the pipeline. I need to do more reading on game engine architecture.

Feel free to post any resources if you have them, anonymous visitor.

**Comment by DanielAustinLee** [comment]
Also trying to figure out how to remove entities from the entity pool without running into Concurrent Modification Exception for the ArrayList. I tried using an iterator in place of .remove() but it hasn't helped.

**Comment by ValorCat** [comment]
Maybe try a CopyOnWriteArrayList? I think its meant for situations like that, but I don't have much experience with it.

**Comment by DanielAustinLee** [comment]
@ValorCat Worked! Thanks for your contributions to anders game!
